export enum tokenSymbols {
    None = 'None',
    USDT = 'USDT',
    USDC = 'USDC',
    USDCe = 'USDC.e',
    DAI = 'DAI',
    BTC = 'BTC',
    WBTC= 'WBTC',
    WETH = 'WETH',
    ETH = 'ETH',
    SOL = 'SOL',
    WSOL = 'WSOL',
    UNI =   'UNI',
    LINK = 'LINK',
    ARB = 'ARB',
    WBNB = 'WBNB',
    AAVE = 'AAVE',
    OP = 'OP',
    AVAX = 'AVAX',
    WAVAX = 'WAVAX',
    GMToken = 'GM',
    GMX = 'GMX',
    DOGE = 'DOGE',
    XRP = 'XRP',
    PEPE = 'PEPE'
}