export enum tokenSymbols {
    USDT = 'USDT',
    USDC = 'USDC',
    USDCe = 'USDC.e',
    DAI = 'DAI',
    WBTC= 'WBTC',
    WETH = 'WETH',
    ETH = 'ETH',
    SOL = 'SOL',
    WSOL = 'WSOL',
    UNI =   'UNI',
    LINK = 'LINK',
    ARB = 'ARB',
    WBNB = 'WBNB',
    AAVE = 'AAVE',
    OP = 'OP',
    AVAX = 'AVAX',
    WAVAX = 'WAVAX',
}